title: "CYBERIA"
description: "Site personnel — Étudiante en cybersécurité à la FSSM"
baseurl: "" # laisser vide pour GitHub Pages
url: "https://itshaname.github.io"
theme: null
plugins: []
markdown: kramdown
favicon_url: "https://raw.githubusercontent.com/ItsHaname/ItsHaname.github.io/main/logo"
